spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/MusicDB?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: mynewpassword
  #mvc:
    #hiddenmethod:
      #filter:
        #enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    #open-in-view: false
    defer-datasource-initialization: true
    #properties:
      #hibernate:
        #format_sql: true
  #sql:
    #init:
      #mode: always